package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"main/src/common/db"
	"main/src/graph/generated"
	"main/src/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	res, err := db.UserCollection.InsertOne(ctx, input)
	if err != nil {
		return nil, err
	}
	fmt.Println(res.InsertedID)
	result := &model.User{
		ID:    res.InsertedID.(primitive.ObjectID).String(),
		Name:  input.Name,
		Age:   input.Age,
		Phone: input.Phone,
	}
	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
