name: build n deploy

on:
  push:
    branches:
      - stg
      - dev

jobs:
  build:
    name: build n deploy
    runs-on: self-hosted
    steps:
      - name: check path
        run: pwd
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

  auto-merge:
    name: auto merge to main branch
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config user.name "RyanBreathings"
          git config user.email "ryan@breathings.co.kr"
      - name: Merge to main
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          COMMIT=$(git rev-parse --short ${GITHUB_SHA})
          git fetch origin $BRANCH
          git checkout main
          git pull
          git merge --no-ff $BRANCH -m "Merge $BRANCH into main"
          git push origin main