name: build n deploy

on:
  push:
    branches:
      - stg
      - dev

jobs:
  build:
    name: build n deploy
    runs-on: self-hosted
    env:
      REPO_DOMAIN: 190009833917.dkr.ecr.us-east-1.amazonaws.com
      REPO_URL: ryan
      CLUSTER_NAME: graphql
      REGION: us-east-1
    steps:
      - name: check path
        run: pwd
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

  auto-merge:
    name: auto merge to main branch
    runs-on: self-hosted
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config user.name "RyanBreathings"
          git config user.email "ryan@breathings.co.kr"
      - name: Prepare
        id: vars
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "COMMIT=$(git rev-parse --short ${GITHUB_SHA})" >> $GITHUB_OUTPUT
      - name: Merge and Push
        run: |
          git fetch origin ${{ steps.vars.outputs.BRANCH }}
          git checkout main
          git pull
          git merge --no-ff ${{ steps.vars.outputs.BRANCH }} -m ${{ steps.vars.outputs.COMMIT }}
          git push origin main
