name: build n deploy

on:
  push:
    branches:
      - stg
      - dev

jobs:
  build:
    name: build n deploy
    runs-on: self-hosted
    steps:
      - name: check path
        run: pwd
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

  auto-merge:
    name: auto merge to main branch
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: merge
        run: |
          git remote set-url origin https://RyanBreathings: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@github.com/JokerTrickster/go_graphQL.git
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff ${{ steps.vars.outputs.BRANCH }} -m ${{ steps.vars.outputs.COMMIT }}
          git push