name: build n deploy

on:
  push:
    branches:
      - stg
      - dev

jobs:
  build:
    name: build n deploy
    runs-on: self-hosted
    steps:
      - name: check path
        run: pwd
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

  auto-merge:
    name: auto merge to main branch
    runs-on: self-hosted
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: prepare
        id: vars
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "COMMIT=$(git rev-parse --short ${GITHUB_SHA})" >> $GITHUB_OUTPUT
      - name: Set up Git
        run: |
          git config user.name "JokerTrickster"
          git config user.email "pkjhj485@gmail.com"
      - name: merge
        run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff ${{ steps.vars.outputs.BRANCH }} -m ${{ steps.vars.outputs.COMMIT }}
          git push