name: deploy PRD

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag to deploy'
        required: true

jobs:
  merge_to_prd:
    name: Merge to PRD
    runs-on: self-hosted
    steps:
      - name: Check Action Actor
        if: github.actor != 'RyanBreathings' && github.actor != 'JokerTrickster'
        run: |
          echo "Actor is wrong: ${{ github.actor }}"
          exit 1

      - name: Set up Git
        run: |
          git config user.name "JokerTrickster"
          git config user.email "pkjhj485@gmail.com"

      - name: Fetch PRD Branch
        run: |
          git fetch origin prd:prd
          git checkout prd
      - name: Checkout Tag and Push to PRD
        run: |
          tags="${{ inputs.tags }}"
          git checkout $tags  # 원하는 태그로 체크아웃
          git push origin $tags:prd  # 해당 태그를 prd 브랜치로 푸시
        env:
          TAGS: ${{ inputs.tags }}