name: deploy PRD

on:
  workflow_dispatch:

jobs:
  merge_to_prd:
    name: Merge to PRD
    runs-on: self-hosted
    steps:
      - name: Check Action Actor
        if: github.actor != 'RyanBreathings' && github.actor != 'JokerTrickster'
        run: |
          echo "Actor is wrong: ${{ github.actor }}"
          exit 1
      - name: Check Action Branch
        run: |
          tag_value="${{ github.event.inputs.tag }}"
          if [ -z "$tag_value" ]; then
            echo "Tag value is empty or not provided."
          else
            echo "Tag value is: $tag_value"
          fi
      - name: Set up Git
        run: |
          git config user.name "JokerTrickster"
          git config user.email "pkjhj485@gmail.com"

      - name: Fetch PRD Branch
        run: |
          git fetch origin prd:prd
          git checkout prd

      - name: Merge STG into PRD
        run: |
          git merge --no-ff stg -m "Merge stg into prd"

      - name: Push to PRD Branch
        run: |
          git push origin prd
