name: Merge Tag to PRD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to merge to PRD'
        required: true

jobs:
  merge_to_prd:
    name: Merge to PRD
    runs-on: self-hosted

    steps:
      - name: Check Action Actor
        if: github.actor != 'RyanBreathings' && github.actor != 'JokerTrickster'
        run: |
          echo "Actor is wrong: ${{ github.actor }}"
          exit 1

      - name: Set up Git
        run: |
          git config user.name "JokerTrickster"
          git config user.email "pkjhj485@gmail.com"

      - name: Fetch PRD Branch
        run: |
          git checkout dev
          git init
          git fetch origin prd:prd
          git checkout prd

      - name: Merge Tag into PRD
        run: |
          tag="${{ github.event.inputs.tag }}"
          git reset --hard $tag
          git push --force origin prd