name: deploy PRD

on:
  create:
    tags:
      - 'v*' # 태그 이름이 'v'로 시작하는 경우에만 동작하도록 설정

jobs:
  merge_to_prd:
    name: Merge to PRD
    runs-on: self-hosted
    steps:
      - name: Check Action Actor
        if: github.actor != 'RyanBreathings' && github.actor != 'JokerTrickster'
        run: |
          echo "Actor is wrong: ${{ github.actor }}"
          exit 1

      - name: Check Action Branch
        if: github.ref != 'refs/heads/stg'
        run: |
          echo "Running branch is wrong: ${{ github.ref }}"
          exit 1

      - name: Set up Git
        run: |
          git config user.name "JokerTrickster"
          git config user.email "pkjhj485@gmail.com"

      - name: Fetch PRD Branch
        run: |
          git fetch origin prd:prd
          git checkout prd

      - name: Merge STG into PRD
        run: |
          git merge --no-ff stg -m "Merge stg into prd"

      - name: Push to PRD Branch
        run: |
          git push origin prd

      - name: Create Release
        run: |
          git tag -a ${{ github.event.ref }} -m "Release ${{ github.event.ref }}"
          git push origin ${{ github.event.ref }}