name: deploy PRD

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag to deploy'
        required: true

jobs:
  merge_to_prd:
    name: Merge to PRD
    runs-on: self-hosted
    steps:
      - name: Check Action Actor
        if: github.actor != 'RyanBreathings' && github.actor != 'JokerTrickster'
        run: |
          echo "Actor is wrong: ${{ github.actor }}"
          exit 1

      - name: Set up Git
        run: |
          git config user.name "JokerTrickster"
          git config user.email "pkjhj485@gmail.com"

      - name: Fetch PRD Branch
        run: |
          git fetch origin prd:prd
          git checkout prd

      - name: Merge STG into PRD
        run: |
          git merge --no-ff stg -m "Merge stg into prd"

      - name: Push to PRD Branch
        run: |
          git push origin prd

      - name: Check Tag and Deploy
        run: |
          tags="${{ inputs.tags }}"
          echo "Selected tag to deploy: $tags"
          # 이제 선택한 태그를 기반으로 배포 스크립트 또는 명령어를 실행할 수 있습니다.
        env:
          TAGS: ${{ inputs.tags }}